version: '3.9'

services:
  db:
    image: postgres:17
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: foodgram
      POSTGRES_USER: foodgram_user
      POSTGRES_PASSWORD: foodgram_password

  backend_migrations:
    image: parfenovakg/infra-backend:latest
    command: >
      bash -c "
      python3 manage.py migrate &&
      python3 manage.py flush --no-input &&   
      python3 manage.py create_test_users --count 10 &&
      python3 manage.py create_test_tags &&
      python3 manage.py create_test_ingredients &&
      python3 manage.py create_test_recipes --count 20 &&
      python3 manage.py create_test_follows --min-follows 1 --max-follows 5 &&
      python3 manage.py create_test_favorites --min-favorites 1 --max-favorites 5 &&
      python3 manage.py create_test_shopping_carts --min-items 1 --max-items 3
      "
    volumes:
      - ../backend/media:/app/media
      - ../backend/staticfiles:/app/static
    depends_on:
      - db
    environment:
      DB_ENABLE_PG: "true"
      DB_HOST: "db"
      DB_NAME: "foodgram"
      DB_USER: "foodgram_user"
      DB_PASSWORD: "foodgram_password"
      DB_PORT: 5432
    env_file:
      - ../backend/.env

  backend:
    image: parfenovakg/infra-backend:latest
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - ../backend/media:/app/media
      - ../backend/staticfiles:/app/static
    depends_on:
      - db
      - backend_migrations
    environment:
      DB_ENABLE_PG: "true"
      DB_HOST: "db"
      DB_NAME: "foodgram"
      DB_USER: "foodgram_user"
      DB_PASSWORD: "foodgram_password"
      DB_PORT: 5432
    env_file:
      - ../backend/.env

  frontend:
    image: parfenovakg/infra-frontend:latest
    volumes:
      - frontend_static:/build_result

  nginx:
    image: nginx:1.23
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - frontend_static:/frontend
      - ../backend/media:/media
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  pg_data:
  frontend_static:
